-- NEXORA WHITELIST DATABASE
-- Run this in Supabase SQL Editor.

create table if not exists public.whitelist_applications (
  id bigint generated by default as identity primary key,
  email text not null,
  twitter_username text not null,
  telegram_username text not null,
  bnb_address text not null,
  created_at timestamptz default now()
);

-- If the table was created previously without Telegram username,
-- this safely adds the new column.
alter table public.whitelist_applications
add column if not exists telegram_username text;

alter table public.whitelist_applications
alter column telegram_username set not null;

alter table public.whitelist_applications enable row level security;

drop policy if exists "public can submit whitelist applications"
on public.whitelist_applications;

create policy "public can submit whitelist applications"
on public.whitelist_applications
for insert
to anon
with check (true);

-- Do NOT create a public SELECT policy.
-- View applications securely in Supabase Dashboard.
