-- NEXORA FINAL V3 DATABASE SETUP
-- Run this in Supabase SQL Editor.

create table if not exists public.whitelist_applications (
  id bigint generated by default as identity primary key,
  email text not null,
  twitter_username text not null,
  telegram_username text not null,
  evm_address text not null,
  referral_code text,
  referred_by text,
  referral_count integer not null default 0,
  campaign_rank bigint,
  created_at timestamptz not null default now()
);

-- Migration for older versions
alter table public.whitelist_applications add column if not exists evm_address text;
alter table public.whitelist_applications add column if not exists referral_code text;
alter table public.whitelist_applications add column if not exists referred_by text;
alter table public.whitelist_applications add column if not exists referral_count integer not null default 0;
alter table public.whitelist_applications add column if not exists campaign_rank bigint;

-- If your old table still uses bnb_address, migrate existing values once.
update public.whitelist_applications
set evm_address = bnb_address
where evm_address is null and bnb_address is not null;

-- Unique participant protection
create unique index if not exists whitelist_email_unique on public.whitelist_applications (lower(email));
create unique index if not exists whitelist_twitter_unique on public.whitelist_applications (lower(twitter_username));
create unique index if not exists whitelist_telegram_unique on public.whitelist_applications (lower(telegram_username));
create unique index if not exists whitelist_evm_unique on public.whitelist_applications (lower(evm_address));
create unique index if not exists whitelist_referral_code_unique on public.whitelist_applications (referral_code);
create unique index if not exists whitelist_campaign_rank_unique on public.whitelist_applications (campaign_rank);

-- Sequence-based campaign rank starting from 1501.
create sequence if not exists public.nexora_campaign_rank_seq start with 1501;

-- Sync sequence if existing campaign ranks are already higher.
select setval(
 'public.nexora_campaign_rank_seq',
 greatest(
   coalesce((select max(campaign_rank) from public.whitelist_applications),1500),
   1500
 ),
 true
);

create or replace function public.nexora_before_insert()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.campaign_rank is null then
    new.campaign_rank := nextval('public.nexora_campaign_rank_seq');
  end if;
  if new.referral_code is null or length(new.referral_code)=0 then
    raise exception 'referral_code is required';
  end if;

  -- Count a valid referral for the owner of the code.
  if new.referred_by is not null and new.referred_by <> new.referral_code then
    update public.whitelist_applications
    set referral_count = referral_count + 1
    where referral_code = new.referred_by;
  end if;
  return new;
end $$;

drop trigger if exists nexora_before_insert_trigger on public.whitelist_applications;
create trigger nexora_before_insert_trigger
before insert on public.whitelist_applications
for each row execute function public.nexora_before_insert();

alter table public.whitelist_applications enable row level security;

drop policy if exists "public can submit whitelist applications" on public.whitelist_applications;
drop policy if exists "public can read leaderboard" on public.whitelist_applications;

create policy "public can submit whitelist applications"
on public.whitelist_applications for insert to anon
with check (true);

-- Public leaderboard exposes only selected columns through the table API.
-- For stronger privacy in production, replace this with a dedicated view/RPC.
create policy "public can read leaderboard"
on public.whitelist_applications for select to anon
using (true);
