-- Run in Supabase SQL Editor
create table if not exists public.whitelist_applications (
  id bigint generated by default as identity primary key,
  email text not null,
  twitter_username text not null,
  bnb_address text not null,
  created_at timestamptz default now()
);

alter table public.whitelist_applications enable row level security;

-- Allow anonymous applications to INSERT only.
create policy "public can submit whitelist applications"
on public.whitelist_applications
for insert
to anon
with check (true);

-- Do NOT create a public SELECT policy.
-- View submissions securely inside Supabase Dashboard.
